- name: Add GPG key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Add repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ buster-pgdg main
    state: present

- name: Install postgresql and python
  apt:
    name:
    - "postgresql-{{ postgresql_version }}"
    - "postgresql-client-{{ postgresql_version }}"
    - "python3-pip"
    - "python-psycopg2"
    - "libpq-dev"
    state: present

- name: Install psycopg2
  pip:
    name: psycopg2
    state: present

- name: Copy config 
  copy:
    src: roles/postgresql/files/postgresql.conf
    dest: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    owner: postgres
    group: postgres
    mode: 0666
    remote_src: no
    force: yes

- name: Copy config
  copy:
    src: roles/postgresql/files/pg_hba.conf
    dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: 0666
    remote_src: no
    force: yes

- name: Copy schema
  copy:
    src: roles/postgresql/files/schema.sql
    dest: /home/postgres/

- name: Create database
  become: true
  become_user: postgres
  postgresql_db:
    name: "{{ POSTGRESQL_DB }}"
    state: present

- name: Setup database
  changed_when: false
  become: true
  become_user: postgres
  shell: "psql -d {{ POSTGRESQL_DB }} -f /home/postgres/schema.sql"

- name: Create user
  become: true
  become_user: postgres
  postgresql_user:
    name: "{{ POSTGRESQL_USER }}"
    password: "{{ POSTGRESQL_PASSWORD }}"
    db: "{{ POSTGRESQL_DB }}"
    priv: "CONNECT/votes:SELECT,INSERT,UPDATE"
    role_attr_flags: NOSUPERUSER

- name: Restart postgresql
  become: true
  systemd:
    name: postgresql
    state: restarted