- name: Update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Set timezone
  timezone:
    name: Europe/Paris

- name: Install packages
  apt:
    name:
    - "git"
    - "unzip"
    - "acl"
    - "vim"
    state: present
